name: Android CI

on:
  push:
    branches:
      - 'v**'
      # master分支不触发工作流
      - '!master'
      # dev_开头的分支不触发工作流
      - '!dev_**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_TOKEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
      SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean with Gradle
        run: ./gradlew clean

      # 对安装包进行签名
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.BUILD_SIGN_KEY_STOREB64 }}
          keystore_password: ${{ secrets.BUILD_SIGN_KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_ALIAS }}
          key_password: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_PASSWORD }}

      # 创建并提交签名后的APK包和源码提交至对应ref_name的tag
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          # 安装包
          artifacts: "sample-gaode/build/outputs/apk/release/*.apk,sample-tencent/build/outputs/apk/release/*.apk"
          artifactErrorsFailBuild: true
          ### 此版本中更改的内容
          # ${{ steps.changelog.outputs.changelog }}
          body:  |
            MapCompose集成高德地图能力，请添加如下依赖：
            ```groovy
              implementation 'io.github.TheMelody:gd_compose:1.0.1'
            ```
            MapCompose集成腾讯地图能力，请添加如下依赖：
            ```groovy
              implementation 'io.github.TheMelody:tencent_compose:1.0.1'
            ```
          token: ${{ secrets.github_token }}
          commit: master
          # tag名称和分支名称保持一致，dev_**分支不触发工作流，vx.x.x分支触发工作流
          tag: ${{ github.ref_name }}

      - name: "Publish Map-Compose"
        run: ./gradlew clean assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
#      - name: "Publish TX Map-Compose"
#        run: ./gradlew clean tencent-map-compose:assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository
#      - name: "Publish GD Map-Compose"
#        run: ./gradlew clean gd-map-compose:assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
#        # 下面的方式：不自动关闭暂存库，手动去执行关闭的话，可以在网页中选择是否删除或者释放：https://s01.oss.sonatype.org/#stagingRepositories
#        #run: ./gradlew clean gd-map-compose:assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository