name: Android CI

on:
  push:
    branches:
      - 'v**'
      # !不触发工作流
      - '!master'
      - '!dev_**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_TOKEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.MAVEN_GPG_KEY_ID }}
      SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean with Gradle
        run: ./gradlew clean

      # 对安装包进行签名
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.BUILD_SIGN_KEY_STOREB64 }}
          keystore_password: ${{ secrets.BUILD_SIGN_KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_ALIAS }}
          key_password: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_PASSWORD }}

      # 创建并提交签名后的APK包和源码提交至对应ref_name的tag
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          # 安装包
          artifacts: "sample-gaode/build/outputs/apk/release/*.apk,sample-tencent/build/outputs/apk/release/*.apk,sample-baidu/build/outputs/apk/release/*.apk"
          artifactErrorsFailBuild: true
          body:  |
            ### 功能更新
            - 新增百度地图能力若干；
            - 移除SDK中高德地图隐藏Logo不合规的问题；
            - Map可组合项新增：onMapClick、onMapLongClick、onMapPOIClick等事件的回调；
            - 升级百度地图SDK最新版本；
            ### 问题修复
            - 修复:sample示例中，安卓11+上的错误上下文；
          token: ${{ secrets.github_token }}
          commit: master
          # tag名称
          tag: ${{ github.ref_name }}

      - name: "Publish Map-Compose"
        run: ./gradlew clean assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
#        # 下面的方式：不自动关闭暂存库，手动去执行关闭的话，可以在网页中选择是否删除或者释放：https://s01.oss.sonatype.org/#stagingRepositories
#        #run: ./gradlew clean gd-map-compose:assembleRelease androidJavaDocJar androidSourcesJar generatePomFileForNexusPublication publishNexusPublicationToSonatypeRepository