name: Android CI

on:
  push:
    branches:
      - 'v**'
      # master分支不触发工作流
      - '!master'
      # dev_开头的分支不触发工作流
      - '!dev_**'
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #- name: build artifact
        #run: mvn clean package

      #- name: Clean with Gradle
        #run: ./gradlew clean
        
      # 生成aar包，只针对已经配置了maven-plugin的module生效
      - name: Generate aar with Gradle
        run: ./gradlew clean build publish

      # 对安装包进行签名
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_b64: ${{ secrets.BUILD_SIGN_KEY_STOREB64 }}
          keystore_password: ${{ secrets.BUILD_SIGN_KEY_STORE_PASSWORD }}
          key_alias: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_ALIAS }}
          key_password: ${{ secrets.BUILD_SIGN_KEY_STORE_KEY_PASSWORD }}

      # 创建并提交签名后的APK包和源码提交至对应ref_name的tag
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          # sample-gaode/build/outputs/apk/release/*.apk,...,sample-tencent/build/repo/io/github/TheMelody/tencent_compose/1.0.0/*.aar
          artifacts: ${{ secrets.BUILD_SOURCE_ARTIFACTS_v1_0_0 }}
          artifactErrorsFailBuild: true
          body:  |
            集成高德地图MapCompose，请添加如下依赖：
            ```groovy
              implementation 'io.github.TheMelody:gd_compose:${{ github.event.inputs.releaseversion }}'
            ```
            集成腾讯地图MapCompose，请添加如下依赖：
            ```groovy
              implementation 'io.github.TheMelody:tencent_compose:${{ github.event.inputs.releaseversion }}'
            ```
            ### 此版本中更改的内容
            ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.github_token }}
          commit: master
          # tag名称和分支名称保持一致，dev_**分支不触发工作流，vx.x.x分支触发工作流
          tag: ${{ github.ref_name }}

      # 上传到maven
      - name: Publish to the Maven Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
